[build]
  publish = "public"
  command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/contact/send"
  to = "/.netlify/functions/mail"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200